# .github/labeler.yml

# Define label rules
label_rules:
  - name: "bug"
    conditions:
      - "bug"
      - "error"
      - "issue"
  - name: "feature"
    conditions:
      - "feature"
      - "enhancement"
  - name: "documentation"
    conditions:
      - "documentation"
      - "docs"
  - name: "needs-review"
    conditions:
      - "needs-review"
      - "review"
  - name: "good-first-issue"
    conditions:
      - "good first issue"
      - "beginner-friendly"

# Define label color (optional)
label_colors:
  - name: "bug"
    color: "d73a4a"
  - name: "feature"
    color: "a2eeef"
  - name: "documentation"
    color: "0075ca"
  - name: "needs-review"
    color: "fbca04"
  - name: "good-first-issue"
    color: "7057ff"
