name: Labeler

on:
  issues:
    types:
      - opened
      - edited
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  labeler:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Labeler Action
        uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
